# Analysis on the graphs that were generated by the simpact program.
# We will first import them and then start the analysis which is comprised of the following:
# 1) Degree distribution of all the graphs
# 2) Graph degree centrality
# 3) Graph transitivity, or average clustering coefficient
# 4) Graph density
# Some of these stats will be shown on a boxplot for the comparison with other graphs.
library(igraph)
library(tidyverse)
g_names <- c('15_0', '15_50', '15_100', '15_150', '15_200', '16_0', '16_50', '16_100', '16_150',
             '16_200', '17_0', '17_50', '17_100', '17_150', '17_200', '18_0', '18_50', '18_100', 
             '18_150', '18_200')
Gs <- list()
Trans <- list()
Density <- list()
Centrality <- list()
Betw <- list()
Eigen <- list()
Dg_dist <- list()
g_sizes <- list()
degrees <- list()

for (i in g_names){
  #Gs[[i]] <- assign(sprintf('g_%s', i), value = list())
  #Trans[[i]] <- assign(sprintf('trans_%s', i), value = list())
  #Density[[i]] <- assign(sprintf('density_%s', i), value = list())
  #Centrality[[i]] <-  assign(sprintf('cent_%s', i), value = list())

  for (j in 1:50) {
    Gs[[i]][[j]] <- graph(t(read_csv(sprintf('~/Transmission_Networks/TN_%s/%d.csv', i, j))))
    Trans[[i]][[j]] <- transitivity(Gs[[i]][[j]], type = 'average')
    Density[[i]][[j]] <- graph.density(Gs[[i]][[j]])
    Centrality[[i]][[j]] <- centr_degree(Gs[[i]][[j]], mode='out')$centralization
    #Betw[[i]][[j]] <- centr_betw(Gs[[i]][[j]])$centralization
    g_sizes[[i]][[j]] <- gsize(Gs[[i]][[j]])
    Eigen[[i]][[j]] <- centr_eigen(Gs[[i]][[j]], directed = TRUE)$value

    d = degree(Gs[[i]][[j]], mode = "out")
    dd = degree.distribution(Gs[[i]][[j]], mode = "out", cumulative = FALSE)
    degree = 1:max(d)
    probability = dd[-1]
    # delete blank values
    nonzero.position = which(probability != 0)
    probability = probability[nonzero.position]
    degree = degree[nonzero.position]
    degrees[[i]][[j]] <- degree
    Dg_dist[[i]][[j]] <- probability
  }
  
  #trans_all[,trans_i] <- c(Trans$i) 
  #density_all[,i] <- c(Density$i)
  #centrality_all[,i] <- c(Centrality$i)
}
Trans <- as.data.frame(Trans)
Density <- as.data.frame(Density)
Centrality <- as.data.frame(Centrality)
Betw <- as.data.frame(Betw)
Degs <- data.frame(degrees,Dg_dist )
boxplot(Betw)
boxplot(Density)
boxplot(Centrality)
write.csv(Trans, file = sprintf('~/Stats/Trans.csv'))
write.csv(Density, file = sprintf('~/Stats/Density.csv'))
write.csv(Centrality, file = sprintf('~/Stats/Centrality.csv'))
write.csv(g_sizes, file = sprintf('~/Stats/Gsize.csv'))
# First we concatenate the lists of degrees and their probabilities per type
get_degree <- function(g_type) {
  Deg_list <- list()
  alist <- list()
  for (i in 1:50){
    dist <- degree_distribution(Gs[[g_type]][[i]], mode = 'out')
    Deg_list <- c(Deg_list, dist)
    alist <- c(alist, 1:length(dist))
    
  }
  deg <- cbind(alist, Deg_list)
  x <- cbind(alist, Deg_list)
  deg <- as.data.frame(x)
  
  write.csv(as.matrix(deg), file = sprintf('~/Degrees/deg_%s.csv', g_type))
            
  }

for (i in g_names){
  get_degree(i)
}

unique_deg <- unique(Deg_list)
max_deg <- max(unique_deg)


get_degree_dist <- function(Gs_type) {

  MaxDeg = rep(0, 50)
  max_prob = 0
  for(i in 1:50) {
    
    DD = Gs_type[[i]]
    MaxDeg[i] = length(DD)
    max_prob = max(DD)
  }
  MaxMax = max(MaxDeg)
  max_max_prob = round(max_prob, digits = 1)
  print(max_max_prob)
  plot(1:MaxDeg[1], Gs_type[[1]], xlim = c(1, MaxMax), type = 'l',
       log='xy', xlab='Log Degree', ylab='LogFrequency')
  
  
  for (i in 2:50) {
    lines(1:MaxDeg[i], Gs_type[[i]])  
  }
} 

# plot_degree_distribution <-function(graph,a) {
#   d = igraph::degree(graph, mode = a)
#   dd = igraph::degree.distribution(graph, mode = a, cumulative = FALSE)
#   degree = 1:max(d)
#   probability = dd[-1]
#   nonzero.position = which(probability != 0)
#   probability = probability[nonzero.position]
#   degree = degree[nonzero.position]
#   
#   TYPE<-paste0("Degree_",a)
#   TITLErev<-paste0("Degree Distribution_",a)
#   plotdata<-cbind(probability,degree)
#   plotdata<-as.data.frame(plotdata)
#   colnames(plotdata)<-c("probability","degree")
#   #graphics::plot(probability ~ degree, log = "xy", xlab = TYPE, ylab = "Probability (log)",
#   #     col = 1, main = TITLErev)
#   ggplot2::ggplot(plotdata, ggplot2::aes(x=degree, y=probability)) +
#     ggplot2::geom_line(color="darkred")+
#     ggplot2::geom_jitter(position = "jitter",color="darkred")+
#     ggplot2::labs(title=TITLErev,
#                   x=TYPE, y = "Probability")+
#     ggplot2::theme_gray()
# }
# 
# 
# plot_degree_distribution(g2, 'out')
# library("poweRlaw")
# library("ggplot2")


# # List of degrees
# g1.degrees <- degree(g1)
# 
# # Let's count the frequencies of each degree
# g1.degree.histogram <- as.data.frame(table(g1.degrees))
# 
# # Need to convert the first column to numbers, otherwise
# # the log-log thing will not work (that's fair...)
# g1.degree.histogram[,1] <- as.numeric(g1.degree.histogram[,1])
# 
# # Now, plot it!
# ggplot(g1.degree.histogram, aes(x = degree(g1), y = Freq)) +
#   geom_point() +
#   scale_x_continuous("Degree\n(nodes with this amount of connections)",
#                      breaks = c(1, 3, 10, 30, 100, 300),
#                      trans = "log10") +
#   scale_y_continuous("Frequency\n(how many of them)",
#                      breaks = c(1, 3, 10, 30, 100, 300, 1000),
#                      trans = "log10") +
#   ggtitle("Degree Distribution (log-log)") +
#   theme_bw()
# trans_data <- data.frame(trans_all, g_names)
# density_data <- data.frame(density_all, g_names)
# cent_data <- data.frame(cent_all, g_names)
# 
# 
# plot(x = 1:length(trans_all), y = trans_all)
# title
# library(ggplot2)
# 
# # deg_ <- degree.distribution(g2,cumulative = T, mode = 'out')
# # plot(deg_)
# # par(new=TRUE)
# # plot(degree.distribution(g2, mode = 'out'))
# # 
# 


ggplot(data = Trans, mapping = aes(x = Trans, y = Trans)) +
  geom_boxplot() + 
  ggtitle('Transitivity') + 
  xlab('Age+Cd4_ART_Intervention') + ylab('Transitivity') 
 
 
ggplot(data = density_data, mapping = aes(x = g_names, y = density_all)) + 
  geom_boxplot() + 
  ggtitle('Graph Density Comparison') +
  xlab('Age+Cd4_ART_Intervention') + ylab('Density')

